# Generated by Django 5.0.3 on 2024-04-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_pub',
            field=models.BooleanField(default=False, verbose_name='Статус продукта'),
        ),
    ]
